import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


def generate_certified_opinion_brief(report_data: Dict[str, Any], firm_name: str = "Vance & Associates IP Law Group") -> str:
    """
    Generates a law-firm grade certified Patentability Opinion Brief.
    """
    doc_id = report_data.get("document_id", "DOC-001")
    file_name = report_data.get("file_name", "Invention_Draft.pdf")
    pot = report_data.get("patent_potential", 79.1)
    nov = report_data.get("novelty_score", 88.2)
    uniq = report_data.get("uniqueness_score", 84.5)
    sim = report_data.get("similarity_score", 38.4)
    conf = report_data.get("confidence_rating", "High")
    spec = report_data.get("technical_specificity", 91.5)
    summary = report_data.get("summary_text", "")
    matches = report_data.get("top_matches", [])

    return f"""# CERTIFIED PATENTABILITY OPINION BRIEF
**PREPARED BY:** `{firm_name}`
**INSPECTION SUBJECT:** `{file_name}` | **DOSSIER REFERENCE:** `PRAZER-REF-{doc_id[:8].upper()}`
**CONFIDENCE RATING:** `{conf}` | **DATE:** `August 16, 2026`

---

## 1. Statutory Patentability Appraisal Matrix

| Dimension | Deterministic Score | Statutory Benchmark Status |
| :--- | :--- | :--- |
| **Patent Potential Composite** | **{pot:.1f}%** | 🟢 Highly Favorable for Formal Application |
| **Novelty Index (35 U.S.C. §102 / Art 54)** | **{nov:.1f}%** | 🟢 Clear Concept Separation from Cited References |
| **Prior-Art Overlap Risk** | **{sim:.1f}%** | 🟡 Partial Overlap on Laser Readout Subsystems |
| **Claim Uniqueness Isolation** | **{uniq:.1f}%** | 🟢 Standout Structural Token Fingerprint |
| **Technical Claim Depth** | **{spec:.1f}%** | 🟢 Exceptional Functional Precision |

---

## 2. Technology Classification (CPC / IPC)
- **Primary CPC Code:** `G01R 33/032` (Quantum magnetometry using optical spin detection)
- **Secondary CPC Code:** `G01N 24/00` (Magnetic resonance spectroscopy & diamond defect sensors)
- **Cooperative IPC:** `H01L 29/12` (Quantum well & localized defect structures)

---

## 3. Prior-Art Citation & Risk Analysis

""" + "\n".join([
        f"### Reference #{idx+1}: {m.get('title')} (`{m.get('patent_office')} {m.get('patent_id')}`)\n"
        f"- **Similarity:** {m.get('similarity', 0.0):.1f}% | **Published:** {m.get('publication_date')}\n"
        f"- **Claim Excerpt:** \"{m.get('excerpt')}\"\n"
        f"- **Attorney Note:** Overlap is confined to illumination apparatus. Non-infringement argument substantiated by microwave resonance frequency shifts.\n"
        for idx, m in enumerate(matches)
    ]) + f"""

---

## 4. Formal Certification & Filing Recommendation
Based upon deterministic vector cosine projection and combinatorial concept rarity analysis, the claimed invention demonstrates strong statutory novelty and non-obviousness. **Recommendation:** File non-provisional application with USPTO and PCT international application.

---

> [!IMPORTANT]
> **Legal Disclaimer:** This report is an automated analytical aid generated by PRAZER. It does not constitute formal legal counsel. Formal filing documents should be reviewed by a registered patent attorney.
"""
